//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backleft_music_UI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbEntities : DbContext
    {
        public mydbEntities()
            : base("name=mydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<songalbum> songalbums { get; set; }
        public DbSet<songartist> songartists { get; set; }
        public DbSet<songinfo> songinfoes { get; set; }
        public DbSet<useraddress> useraddresses { get; set; }
        public DbSet<usercreditcardinfo> usercreditcardinfoes { get; set; }
        public DbSet<userinfo> userinfoes { get; set; }
        public DbSet<userplaylist> userplaylists { get; set; }
        public DbSet<userpurchas> userpurchases { get; set; }
    }
}
