//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backleft_music_UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class songalbum
    {
        public songalbum()
        {
            this.songinfoes = new HashSet<songinfo>();
        }
    
        public int songAlbumID { get; set; }
        public string songAlbumName { get; set; }
        public string songAlbumLabel { get; set; }
        public string songAlbumYear { get; set; }
    
        public virtual ICollection<songinfo> songinfoes { get; set; }
    }
}
