//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backleft_music_UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class useraddress
    {
        public useraddress()
        {
            this.userinfoes = new HashSet<userinfo>();
        }
    
        public int userAddID { get; set; }
        public string userStreet { get; set; }
        public string userCity { get; set; }
        public string userState { get; set; }
        public string userZip { get; set; }
        public string userCountry { get; set; }
    
        public virtual ICollection<userinfo> userinfoes { get; set; }
    }
}
