//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backleft_music_UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class userplaylist
    {
        public userplaylist()
        {
            this.songinfoes = new HashSet<songinfo>();
        }
    
        public int userplaylistID { get; set; }
        public string userplaylistNAME { get; set; }
    
        public virtual ICollection<songinfo> songinfoes { get; set; }
    }
}
