//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backleft_music_UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public int iduserInfo { get; set; }
        public string userFirstName { get; set; }
        public string userLastName { get; set; }
        public Nullable<int> userAddID { get; set; }
        public Nullable<int> userPurchasesID { get; set; }
        public string userEmail { get; set; }
        public Nullable<int> userCreditCardID { get; set; }
        public string userPhoneNumber { get; set; }
    
        public virtual useraddress useraddress { get; set; }
        public virtual usercreditcardinfo usercreditcardinfo { get; set; }
        public virtual userpurchas userpurchas { get; set; }
    }
}
