//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backleft_music_UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class usercreditcardinfo
    {
        public usercreditcardinfo()
        {
            this.userinfoes = new HashSet<userinfo>();
        }
    
        public int userCreditCardID { get; set; }
        public string userCardType { get; set; }
        public string userCreditCardNumber { get; set; }
        public string userCardExpDate { get; set; }
        public Nullable<int> userCardCCV { get; set; }
        public string userCardName { get; set; }
    
        public virtual ICollection<userinfo> userinfoes { get; set; }
    }
}
